# データの連結

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3, 3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 列方向に連結

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

## 行方向に連結

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0, 1, 2], index=['T', 'U', 'V'])

In [7]:
ser2 = Series([3, 4], index=['X', 'Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
pd.concat([ser1, ser2], axis=1, keys=['cat1', 'cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [15]:
df1 = DataFrame(np.random.randn(4, 3), columns=['X', 'Y', 'Z'])

In [16]:
df1

X         Y         Z
0  1.242353 -0.309249  0.289885
1  1.063451  0.128782  0.042441
2 -0.523881 -2.594776 -0.647010
3 -0.998205 -1.452273 -0.476235

In [17]:
df2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [18]:
df2

Y         Q         X
0 -0.037129  0.059768 -1.649101
1 -2.482105 -1.802293  1.830953
2 -0.711873  0.158742 -0.147931

In [19]:
pd.concat([df1, df2])

Q         X         Y         Z
0       NaN  1.242353 -0.309249  0.289885
1       NaN  1.063451  0.128782  0.042441
2       NaN -0.523881 -2.594776 -0.647010
3       NaN -0.998205 -1.452273 -0.476235
0  0.059768 -1.649101 -0.037129       NaN
1 -1.802293  1.830953 -2.482105       NaN
2  0.158742 -0.147931 -0.711873       NaN