In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 平方根:np.sqrt(array)

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.13480744,  0.52702508,  0.88281382,  1.77722363,  0.52148611,
       -0.18536177,  0.60831275, -0.27880688, -0.64222056, -0.17778866])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ 3.05180548,  0.56407388, -0.03398031, -0.22594699, -0.41504074,
        0.88181743,  1.12820839, -0.54590127, -0.05849399, -1.4041734 ])

## 要素の足し算

In [10]:
np.add(A, B)

array([ 2.91699804,  1.09109896,  0.84883352,  1.55127664,  0.10644537,
        0.69645565,  1.73652114, -0.82470815, -0.70071455, -1.58196206])

In [ ]:
3

In [11]:
np.maximum(A, B)

array([ 3.05180548,  0.56407388,  0.88281382,  1.77722363,  0.52148611,
        0.88181743,  1.12820839, -0.27880688, -0.05849399, -0.17778866])