## arrayの入出力

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

### バイナリデータとして保存

In [4]:
np.save('my_array', arr)

In [7]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [14]:
arr1 = np.load('my_array.npy')

In [15]:
arr2 = np.arange(10)

In [16]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr1

array([0, 1, 2, 3, 4])

### zip形式で保存

In [19]:
np.savez('ziparrays.npz', x=arra1, y=arr2)

In [20]:
archive_array = np.load('ziparrays.npz')

In [21]:
archive_array

In [22]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [23]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

In [25]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [26]:
np.savetxt('test_text.txt', arr, delimiter=',')

In [27]:
!cat test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00


In [29]:
arr = np.loadtxt('test_text.txt', delimiter=',')

In [30]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.]])