In [1]:
import numpy as np

In [2]:
my_list1 = [1, 2, 3, 4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11, 22, 33, 44]

In [6]:
my_lists = [my_list1, my_list2]

In [7]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [8]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

### shape:(行, 列)

In [10]:
my_array2.shape

(2, 4)

### dtype:格納されているデータ型

In [11]:
my_array2.dtype

dtype('int64')

### np.zeros(n):引数の数値の分だけ0のarrayを作る

In [12]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
my_zeros = np.zeros(5)

In [15]:
my_zeros.dtype

dtype('float64')

### np.ones(n):全ての要素が1のarrayを返す

In [17]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [18]:
np.ones((5, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### np.empty():空のarrayを返す

In [20]:
np.empty((3, 4))

array([[  0.00000000e+000,   2.68678417e+154,   2.96439388e-323,
          4.94065646e-324],
       [  0.00000000e+000,   3.76231786e+174,   0.00000000e+000,
          9.34861458e-067],
       [  0.00000000e+000,   5.93854595e-038,   0.00000000e+000,
          8.34402697e-309]])

### np.eye(n):単位行列

In [23]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### np.arange(n):n-1までのarrayを返す

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

### np.arange(x, y, z):xからy-1までz飛ばし

In [25]:
np.arange(0, 50, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

# numpyを使った計算

In [1]:
import numpy as np

In [2]:
5 / 2

2.5

In [3]:
arr1 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])

In [4]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [5]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [6]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])